### ISSUE TITLE
Cannot play mp3 files

### ISSUE THREAD

**Issue by thompsond** [RalleYTN/SimpleAudio#2]
I compiled the source files and referenced libraries into a single jar file. When I use the StreamedAudio class to play an mp3 file, including the one provided in the test folder, an AudioException is thrown: de.ralleytn.simple.audio.AudioException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1155)
	at de.ralleytn.simple.audio.AbstractAudio.getAudioInputStream(AbstractAudio.java:305)
	at de.ralleytn.simple.audio.StreamedAudio.open(StreamedAudio.java:295)
        at com.AVMisc.AVMisc$2.run(AVMisc.java:212)

WAV files and other files will play.

**Comment by RalleYTN** [comment]
Does it play when you use BufferedAudio?
Could you provide the source code with which you are loading the file?

**Comment by thompsond** [comment]
BufferedAudio does not work as well. My project is in Java 8 so I compiled the source for version 2 into a Java 8 jar. Is there more that I need to change other than removing the module-info.java?
Here is my method:

private void playAudio() {
		if(!playingAudio.get()) {
			System.out.print("Enter the path of the audio file to play: ");
			String fileName = sc.nextLine();
			playingAudioThread = new Thread() {
				@Override
				public void run() {
					try {
						if(!Files.exists(Paths.get(fileName))) {
							throw new FileNotFoundException(String.format("The file '%s' does not exist.", fileName));
						}
						playingAudioFileName = fileName;
						audio = new StreamedAudio(playingAudioFileName);
						audio.addAudioListener(event -> {
							if(event.getType() == AudioEvent.Type.REACHED_END) {
								event.getAudio().close();
							}
						});
						audio.open();
						audio.play();
						playingAudio.set(true);
					}
					catch(AudioException | FileNotFoundException e) {
						e.printStackTrace();
					}
				}
			};
			playingAudioThread.start();
		}
	}

**Comment by thompsond** [comment]
BufferedAudio does not work as well. My project is in Java 8 so I compiled the source for version 2 into a Java 8 jar. Is there more that I need to change other than removing the module-info.java?
Here is my method:
`private void playAudio() {
if(!playingAudio.get()) {
System.out.print("Enter the path of the audio file to play: ");
String fileName = sc.nextLine();
playingAudioThread = new Thread() {
@override
public void run() {
try {
if(!Files.exists(Paths.get(fileName))) {
throw new FileNotFoundException(String.format("The file '%s' does not exist.", fileName));
}
playingAudioFileName = fileName;
audio = new StreamedAudio(playingAudioFileName);
audio.addAudioListener(event -> {
if(event.getType() == AudioEvent.Type.REACHED_END) {
event.getAudio().close();
}
});
audio.open();
audio.play();
playingAudio.set(true);
}
catch(AudioException | FileNotFoundException e) {
e.printStackTrace();
}
}
};
playingAudioThread.start();
}
}`

**Comment by thompsond** [comment]
It works now, I was missing a library.
